name: Resolve docker metadata
description: Resolve docker metadata such as tags and OCI labels.

inputs:
  title:
    description: Human-readable name of this image.
    required: true
  image-name:
    description: The image name, optionally prepended by a registry URL.
    required: true
  platforms:
    description: "List of platforms to build"
    required: true
    default: "linux/amd64,linux/arm64"
  release:
    description: Set to 'true' to treat this version as a release. 'version' must then be compatible with SemVer.
    required: false
    default: "false"
  version:
    description: The version identifier.
    required: true

outputs:
  annotations:
    description: A line-separated list of OCI annotations to pass to the docker build command.
    value: ${{ steps.labels-metadata.outputs.annotations }}
  labels:
    description: A line-separated list of OCI labels to pass to the docker build command.
    value: ${{ steps.labels-metadata.outputs.labels }}
  tags:
    description: A comma-separated list of tags to pass to the docker build command.
    value: ${{ steps.tags-metadata.outputs.tags }}

runs:
  using: composite
  steps:
    - name: Compute tags output
      id: tags-metadata
      shell: bash
      run: |
        DOCKER_IMAGE=${{ inputs.image-name }}
        RELEASE=${{ inputs.release }}
        VERSION=${{ inputs.version }}
        COMMIT_SHA=${{ github.sha }}
        REF_NAME_TAG=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]/-/g')

        if [ "$RELEASE" = "true" ]; then
          MINOR=${VERSION%.*}
          MAJOR=${MINOR%.*}
          TAGS="${DOCKER_IMAGE}:v${VERSION},${DOCKER_IMAGE}:version-${VERSION},${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
        else
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:edge"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="${TAGS},${DOCKER_IMAGE}:${REF_NAME_TAG}-${COMMIT_SHA:0:7}-$(date --utc +%Y%m%d%H%M%SZ)"
          fi
        fi

        echo "tags=${TAGS}" >> $GITHUB_OUTPUT

    - name: Compute annotations and labels output
      id: labels-metadata
      uses: actions/github-script@v7
      env:
        CONTAINER_TITLE: ${{ inputs.title }}
        CONTAINER_VERSION: ${{ inputs.version }}
      with:
        script: |
          const labels = [
            `org.opencontainers.image.title=${process.env.CONTAINER_TITLE}`,
            "org.opencontainers.image.description=${{ github.event.repository.description }}",
            "org.opencontainers.image.url=${{ github.event.repository.html_url }}",
            "org.opencontainers.image.source=${{ github.event.repository.html_url }}",
            `org.opencontainers.image.version=${process.env.CONTAINER_VERSION}`,
            `org.opencontainers.image.created=${new Date().toISOString()}`,
            "org.opencontainers.image.revision=${{ github.sha }}",
            "org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}",
          ];

          const platforms = '${{ inputs.platforms }}'.split(',');
          const targets = ['index-descriptor', 'manifest-descriptor', 'manifest'];
          if (platforms.length > 1) {
            targets.push('index');
          }

          core.setOutput("annotations", labels.map((x) => `${targets.join(',')}:${x}`).join('\n'));
          core.setOutput("labels", labels.join('\n'));
